language: node_js
node_js:
  - "6.9.1"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g wintersmith

script:
  - ng build && mv dist/* .

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
