language: node_js
node_js:
- 6.9.1
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
script:
- ng build --prod
after_success:
- firebase deploy --token=${FIREBASE_API_TOKEN}
deploy:
  provider: heroku
  app: ctnet
  api_key:
    secure: ZgZiR3x6UeBkL5z9qQ65NHn5yLYwJLTwWoE3W2rrLQSm9oG/LkdWC3T2MmwHH4gxrECpXSKktK+sKYztH31dDNvePkdAlQk6aplH+8B+DOIwJJL3BvvWDIdLCCVYPy/y7NI9gwcGQxoCxVLWzHAZiiaJhBokaEfD7QgV0tBTXbhVxAJpkdYMPhQIr+c6OqEHFQXcLtiU2n7f0jsBFeuayG5gqkZNvV28f3rIREPpx6Fko8HETNM/HgpPoWkS864CYqDp2U3WQ38XZc6wuWP0WOVKHS+Y+hc7r2RZBgTiYMPjgZ7nf8PNPUF1V/CVNlyZx+tOrS1vUyGU6X0oKJg4/EsDCpjXRpRIOt1YC/+99Fq1n1HGVcq/yvBKXwnrxubFOvmnn8tL1PAgIvbymdx62z281V7uCC+Wpg7QlAluyVoGPDphlvniwWgYYIxBuSQfXFQP+L60Wyo3KOdbB7iik8KQwNqmPli+1bIivToQ6EJiIdEb/kWrxEbRvaEAmJ9INa5byY9+c9mSl2mWnqrn4swph2rF8hg3JDxiYc/uPregW4Zl7g5Eal3MebMTTwkbrIVjhhe1oU7nQWDD5yDSullDuWeRw1sHdFTp1FVChNZCQ5KH4gBCeZWZlqTr+enh1rTSdKmcaU0saQyC1nYfCLrBkp5IaveyGPLJ2emTdmE=
