language: 
  node_js
node_js:
  - 6.9.1
branches:
  only:
  - 
cache:
  directories:
  - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g firebase-tools
script:
  #- karma start --single-run
  - ng build --prod
after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}