language: node_js
node_js:
- 6.9.1
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
script:
- ng build --prod
after_success:
- firebase deploy --token=${FIREBASE_API_TOKEN}
deploy:
  provider: heroku
  app: ctnet
  api_key:
    secure: ${HEROKU_API_KEY}
